# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://AguaClara.github.io"

# Name of website
title: AguaClara Plant Operations Smartphone Tracker (POST)

# Short description of your site
description: A website tracker for POST water treatment plant data

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "not_in_use"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-XXXXXXX-1"

# Local port to serve on 
port: 4044